// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlaJOxbCDFL4DQ79bSTSMiR9KdesjDFE',
    appId: '1:229357556827:web:363d9307a3bb27db905b7e',
    messagingSenderId: '229357556827',
    projectId: 'extracurriculares-69e35',
    authDomain: 'extracurriculares-69e35.firebaseapp.com',
    databaseURL: 'https://extracurriculares-69e35-default-rtdb.firebaseio.com',
    storageBucket: 'extracurriculares-69e35.firebasestorage.app',
    measurementId: 'G-QFE14SXKSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwDAMjuooHJ9b_RYpoCVdDvRKzfCKj25o',
    appId: '1:229357556827:android:aeae59a39f6994ca905b7e',
    messagingSenderId: '229357556827',
    projectId: 'extracurriculares-69e35',
    databaseURL: 'https://extracurriculares-69e35-default-rtdb.firebaseio.com',
    storageBucket: 'extracurriculares-69e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdbIwZTZeITiywqeo6jFBtuYy7lZ34b1I',
    appId: '1:229357556827:ios:7d8f3e75b46ad3a3905b7e',
    messagingSenderId: '229357556827',
    projectId: 'extracurriculares-69e35',
    storageBucket: 'extracurriculares-69e35.appspot.com',
    iosBundleId: 'com.example.aplicacion',
  );
}